//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageKeyValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageKeyValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CooKaiApprovalWeb.Utilities.LanguageKeyValues", typeof(LanguageKeyValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認依頼中が **{0}** 件、未回答が **{1}** 件あります。.
        /// </summary>
        internal static string ApprovalStatusCardBodyText {
            get {
                return ResourceManager.GetString("ApprovalStatusCardBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認されました.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付ファイル.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coo kai Bot へようこそ.
        /// </summary>
        internal static string BotWelcomeText {
            get {
                return ResourceManager.GetString("BotWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメントを入力してください。.
        /// </summary>
        internal static string CommentPlaceHolderText {
            get {
                return ResourceManager.GetString("CommentPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメント.
        /// </summary>
        internal static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        internal static string CreateApprovalRequestText {
            get {
                return ResourceManager.GetString("CreateApprovalRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簡易表示.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理済み.
        /// </summary>
        internal static string outOf {
            get {
                return ResourceManager.GetString("outOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認待.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 却下.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 却下されました.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請は既に返答がありました。.
        /// </summary>
        internal static string RequestAlreadyApprovedOrRejected {
            get {
                return ResourceManager.GetString("RequestAlreadyApprovedOrRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to さんからの承認依頼.
        /// </summary>
        internal static string RequestedByTextForApprover {
            get {
                return ResourceManager.GetString("RequestedByTextForApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to さんからの閲覧依頼.
        /// </summary>
        internal static string RequestedByTextForViewer {
            get {
                return ResourceManager.GetString("RequestedByTextForViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請は一部回答が来ているため、削除ができません。.
        /// </summary>
        internal static string RequestInProgressError {
            get {
                return ResourceManager.GetString("RequestInProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認依頼への回答ありがとうございます。.
        /// </summary>
        internal static string RequestProcessed {
            get {
                return ResourceManager.GetString("RequestProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回答しました.
        /// </summary>
        internal static string Responded {
            get {
                return ResourceManager.GetString("Responded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了条件：全員の承認が必要.
        /// </summary>
        internal static string ResponsesTextMultiple {
            get {
                return ResourceManager.GetString("ResponsesTextMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了条件：1人の承認があれば良い.
        /// </summary>
        internal static string ResponsesTextSingle {
            get {
                return ResourceManager.GetString("ResponsesTextSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細表示.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーがみつかりません。.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請を表示.
        /// </summary>
        internal static string ViewApprovalRequestsText {
            get {
                return ResourceManager.GetString("ViewApprovalRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認状況.
        /// </summary>
        internal static string YouApprovalStatusText {
            get {
                return ResourceManager.GetString("YouApprovalStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたの申請は.
        /// </summary>
        internal static string YourRequestText {
            get {
                return ResourceManager.GetString("YourRequestText", resourceCulture);
            }
        }
    }
}
