//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprovalRequest()
        {
            this.ApprovalLevels = new HashSet<ApprovalLevel>();
            this.RequestAttachments = new HashSet<RequestAttachment>();
            this.RequestRemarks = new HashSet<RequestRemark>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentApprovalRequestId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public System.Guid RequesterUserId { get; set; }
        public string AttachementUrl { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public long TenantInfoId { get; set; }
        public Nullable<int> TotalLevel { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public Nullable<System.Guid> TemplateId { get; set; }
        public Nullable<System.DateTime> DesiredCompletionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalLevel> ApprovalLevels { get; set; }
        public virtual ApprovalStatu ApprovalStatu { get; set; }
        public virtual Template Template { get; set; }
        public virtual TenantInfo TenantInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAttachment> RequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestRemark> RequestRemarks { get; set; }
    }
}
