//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRequestApproverOrViewer
    {
        public System.Guid Id { get; set; }
        public System.Guid ApprovalLevelId { get; set; }
        public System.Guid UserId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
        public bool IsApprover { get; set; }
        public string GroupInfo { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ApprovalLevel ApprovalLevel { get; set; }
        public virtual ApprovalStatu ApprovalStatu { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
