//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestRemark
    {
        public System.Guid Id { get; set; }
        public System.Guid ApprovalRequestId { get; set; }
        public string Remark { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedUserId { get; set; }
    
        public virtual ApprovalRequest ApprovalRequest { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
