//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateLevel()
        {
            this.TemplateApproverOrViewers = new HashSet<TemplateApproverOrViewer>();
        }
    
        public System.Guid Id { get; set; }
        public string LevelName { get; set; }
        public int LevelNo { get; set; }
        public bool IsSingleApprover { get; set; }
        public System.Guid TemplateId { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsApproveOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateApproverOrViewer> TemplateApproverOrViewers { get; set; }
        public virtual Template Template { get; set; }
    }
}
