//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateApproverOrViewer
    {
        public System.Guid Id { get; set; }
        public System.Guid TemplateLevelId { get; set; }
        public System.Guid UserId { get; set; }
        public bool IsApprover { get; set; }
        public string GroupInfo { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual TemplateLevel TemplateLevel { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
