//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooKaiApprovalWeb.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.ApprovalRequestApproverOrViewers = new HashSet<ApprovalRequestApproverOrViewer>();
            this.ApprovalRequests = new HashSet<ApprovalRequest>();
            this.RequestAttachments = new HashSet<RequestAttachment>();
            this.RequestRemarks = new HashSet<RequestRemark>();
            this.TemplateApproverOrViewers = new HashSet<TemplateApproverOrViewer>();
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public System.Guid Id { get; set; }
        public string UserPrincipalName { get; set; }
        public string TeamUserId { get; set; }
        public System.Guid AadObjectId { get; set; }
        public long TenantId { get; set; }
        public string Name { get; set; }
        public string ConversationId { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalRequestApproverOrViewer> ApprovalRequestApproverOrViewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalRequest> ApprovalRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAttachment> RequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestRemark> RequestRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateApproverOrViewer> TemplateApproverOrViewers { get; set; }
        public virtual TenantInfo TenantInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
