const Laguage = {
  en: {
    CreateRequest: 'Create Request',
    TotalRequested: 'Total Requested',
    AverageApprovedRequested: 'Average Approved',
    AwaitingApproval: 'Awaiting',
    ApprovedApproval: 'Approved',
    PendingApproval: 'Pending',
    RejectedApproval: 'Rejected',
    RequestedApproval: 'Requested',
    TotalRequestedByApprover: 'Approver Requested',
    AverageApprovedByApprover: 'Average Approved',
    ApprovedByApprover: 'Approved',
  },
  jap: {
    CreateRequest: '新規作成',
    TotalRequested: '申請済み',
    AverageApprovedRequested: '回答取得平均日数',
    AwaitingApproval: '進行中',
    ApprovedApproval: '承認',
    PendingApproval: '未処理',
    RejectedApproval: '却下',
    RequestedApproval: 'Requested approval',
    TotalRequestedByApprover: '承認依頼',
    AverageApprovedByApprover: '処理完了平均日数',
    ApprovedByApprover: '処理済み',
    Title: 'タイトル',
    ApplicantName: '申請者',
    Attachement: '添付',
    Requestedon: '申請日時',
    Approver: '承認者',
    ResponseDate: '承認日時',
    Status: 'ステータス',
    MeAsApplication: '自身の申請',
    AllRequest: '全ての申請',
    MeAsApprover: '自身が承認者',
    AllRequestTome: '全ての承認申請',
    Responded: '処理済み',
    MeAsReader: '自身が閲覧者',
    AllRequesterasReader: '全ての閲覧申請',
    Search: '検索',
    SearchByDateRange: '申請日付検索',
    Sunday: '日',
    Monday: '月',
    Tuesday: '火',
    Wednessday: '水',
    Thursday: '木',
    Friday: '金',
    Saturday: '土',
    // -------------- Details Screen -------------------------
    TitleDetailsOfRequest: ' 申請詳細',
    Delete: '削除する',
    Close: '閉じる',
    EditRequest: '申請を編集する',
    FilesTotal: 'コメント欄',
    MB: 'MB',
    Reader: '閲覧者',
    Approve: '承認する',
    Reject: '却下する',
    ApprovingRequest: '申請を承認する',
    WriteAComment: 'メッセージを入力（または、空白のまま送信)',
    RejectingRequest: ' 申請を却下する',
    Dashboard: 'ダッシュボード',
    NoItemDisplay: 'アイテムがありません。',
    RequestSuccessfull: '申請を完了しました',
    RequestFailed: '申請に失敗しました',

    ApproverViewApproved: '承認しました',
    ApproverViewRejected: '却下しました',
    RequesterVeiwApproved: '承認されました',
    RequesterVeiwRejected: '却下されました',

    RequestCreator: '申請者',
    RequestCreateDate: '申請日時',
    AddAttachement: 'ファイル添付',
    AttachmentList: '添付リスト',
    TitlePlaceHolder: 'タイトルを入力',
    TitleRequiredError: 'タイトルを入力',
    DetailsPlaceHolder: '本文を入力',
    DetailsRequiredError: '本文を入力',
    Save: '申請',
    UploadFromComputer: 'コンピュータからアップロード',
    DeleteRequest: '申請の削除',
    WantToDelete: '以下の申請を削除しますか？',
    Cancel: 'キャンセル',
    DeleteRequestBtn: '削除',
    RequestDeletedSuccess: '申請の削除が成功しました。',
    RequestDeletedFailed: '削除の処理が失敗しました。',
    selectReaderPlaceholder: '閲覧者名を入力',
    selectApproverPlaceholder: '承認者名を入力',
    needEveryOneApproval: '全員の承認が必要',
    justASingleApproval: 'いずれか1人の承認',
    needEveryOneApprovalForDetails: '完了条件：全員の承認',
    justASingleApprovalForDetails: '完了条件：いずれか1人の承認',
    TitleEdit: '編集',
    RequiredWithUnicode: '【必須】',
    AttachmentErrorHeader: '添付ファイルエラー',
    AttachmentErrorLine1: '添付ファイルの総容量が制限サイズを超えています。',
    AttachmentErrorLine2: '一度に添付可能な総容量は10MBまでです。',
    Return: '戻る',
    GenericError: 'エラーが発生しました。', // An error occured,
    SuggestedPeople: 'おすすめのユーザー',
    SuggestedContacts: 'おすすめの連絡先',
    NoResultsFound: '検索した結果がありません',
    Loading: 'ロード中',
    PeoplePickerSuggestionsavailable: 'ユーザーのおすすめ機能を利用できます',
    Please: '続けるには',
    Login: 'ログイン',
    ToContinue: 'してください',
    MessagePrefix: '「',
    MessagePostfix: '」',
    ApprovalMessage: 'を承認しました。',
    RejectedMessage: 'を却下しました。',
    ApproveRejectError: 'を承認できませんでした。',
    IAppliedForIt: 'を申請しました。',
    WasDeleted: 'を削除しました。',
    CouldNotApply: 'を申請できませんでした。',
    BtnAddApprover: '承認者を追加',
    FixedPhraseRegistration: 'テンプレート',
    templateName: 'テンプレート名',
    FixedPhraseRegistrationModalTitle: 'テンプレート追加',
    TemplateBody: '本文',
    TemplateBodyPlaceholder: '本文入力',
    LevelNo: 'ステップ',
    TemplateApprover: '承認者',
    TemplateRegistration: '登録',
    TemplateTitle: 'テンプレート',
    templatePlaceholder: 'テンプレートを選択してください',
    Remarks: '備考',
    CurrentLevelTitle: '現在のステップ',
    TitleRecentRemarks: '最近入力された備考',
    RemarksPlaceholder: '備考入力',
    AppBarBody: '本文',
    AppBarAttachementRemarks: '添付または備考',
    BtnSaveAttachnentRemarks: '添付と備考を登録',
    RequestId: '申請ID',
    ApproverHistory: '承認履歴',
    StatusByUser: '個別ステータス',
    FinalStatus: '全体ステータス',
    StepName: 'ステップ名',
    DownloadForm: '帳票出力',
    StepNamePlaceholder: 'ステップ名を入力',
    IsOnlyApprove: '承認のみを許可する​',
    CreateTemplate: 'テンプレート作成',
    TemplateList: 'テンプレート一覧',
    DesiredCompletionDate: '完了希望日',
    Active: '有効',
    Inactive: '無効',
    TotalStep: 'ステップ数',
    Toggle: '有効/無効',
    ActiveConfirmation: 'を有効にしますか？',
    InactiveConfirmation: 'を無効にしますか？',
    DeleteConfirmation: 'を削除してもよろしいですか？',
    SearchPlaceholder: 'テンプレート名または本文を入力してください',
    TemplateManagement: 'テンプレート管理',
  },
};

export default Laguage;
