export const LOADING_ACTION = 'GET_SINGLE_REQUEST';
export const FAILURE_ACTION = 'GET_SINGLE_REQUEST_FAILURE';

export const GET_REQUEST_LIST_SUCCESS = 'GET_REQUEST_LIST_SUCCESS';
export const STORE_STATUS_CODE = 'STORE_STATUS_CODE';
export const GET_REQUEST_STATS_SUCCESS = 'GET_REQUEST_STATS_SUCCESS';
export const GET_REQUEST_LATEST_STATUS = 'GET_REQUEST_LATEST_STATUS';
export const ADD_NEW_REQUEST_SUCCESS = 'ADD_NEW_REQUEST_SUCCESS';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const RESET_REQUEST_LIST = 'RESET_REQUEST_LIST';
export const STOP_REQUEST_LIST = 'STOP_REQUEST_LIST';
export const LIST_LOADING_ACTION = 'LIST_LOADING_ACTION';
export const GET_CURRENT_STATUS_ID = 'GET_CURRENT_STATUS_ID';
